import { buildPose, buildPoseSecondary, mergePoses } from './rig'
import type { ExerciseMotionData, Pose } from './types'

// Shared limb-length presets. Passing the SAME lengths to both poseA and
// poseB (only angles differ) is what guarantees the bone-length invariant
// checked by boneLengths.test.ts -- see rig.ts for the mechanism.
const COMPACT = { torsoLen: 43, upperArmLen: 25, forearmLen: 22, thighLen: 33, shankLen: 33, neckLen: 13 }
const SEATED = { torsoLen: 50, upperArmLen: 31, forearmLen: 27, thighLen: 40, shankLen: 38, neckLen: 16 }

const HANG_LEGS = { thighLen: 30, shankLen: 28 }

export const motionGuides: Record<string, ExerciseMotionData> = {
  // ---------------------------------------------------------------- warmup
  warmup_bar_hang: {
    key: 'warmup_bar_hang',
    name: 'Bar Hang',
    equipment: 'bodyweight',
    restSec: 0,
    timeBased: true,
    poseA: buildPose({
      hip: { x: 120, y: 96 },
      torsoAngle: -88,
      upperArmAngle: -100,
      forearmAngle: -80,
      thighAngle: 100,
      shankAngle: 115,
      ...COMPACT,
      ...HANG_LEGS,
    }),
    poseB: buildPose({
      hip: { x: 120, y: 96 },
      torsoAngle: -88,
      upperArmAngle: -100,
      forearmAngle: -80,
      thighAngle: 108,
      shankAngle: 106,
      ...COMPACT,
      ...HANG_LEGS,
    }),
    frameShapes: [{ kind: 'rect', x: 95, y: 2, w: 53, h: 4, rx: 2, fill: 'bar' }],
  },

  warmup_deep_squat_hold: {
    key: 'warmup_deep_squat_hold',
    name: 'Deep Squat Hold',
    equipment: 'bodyweight',
    restSec: 0,
    timeBased: true,
    poseA: buildPose({
      hip: { x: 130, y: 110 },
      torsoAngle: -70,
      upperArmAngle: 129,
      forearmAngle: 118,
      thighAngle: 165,
      shankAngle: 70,
      ...COMPACT,
    }),
    poseB: buildPose({
      hip: { x: 130, y: 108 },
      torsoAngle: -72,
      upperArmAngle: 131,
      forearmAngle: 120,
      thighAngle: 168,
      shankAngle: 68,
      ...COMPACT,
    }),
  },

  warmup_horizontal_arm_swings: {
    key: 'warmup_horizontal_arm_swings',
    name: 'Horizontal Arm Swings',
    equipment: 'bodyweight',
    restSec: 0,
    poseA: buildPose({
      hip: { x: 120, y: 84 },
      torsoAngle: -90,
      upperArmAngle: 165,
      forearmAngle: 165,
      thighAngle: 90,
      shankAngle: 90,
      ...COMPACT,
    }),
    poseB: buildPose({
      hip: { x: 120, y: 84 },
      torsoAngle: -90,
      upperArmAngle: 15,
      forearmAngle: 15,
      thighAngle: 90,
      shankAngle: 90,
      ...COMPACT,
    }),
  },

  warmup_torso_rotation_swings: {
    key: 'warmup_torso_rotation_swings',
    name: 'Torso Rotation Swings',
    equipment: 'bodyweight',
    restSec: 0,
    poseA: buildPose({
      hip: { x: 120, y: 84 },
      torsoAngle: -85,
      upperArmAngle: -30,
      forearmAngle: -20,
      thighAngle: 88,
      shankAngle: 92,
      ...COMPACT,
    }),
    poseB: buildPose({
      hip: { x: 120, y: 84 },
      torsoAngle: -100,
      upperArmAngle: -55,
      forearmAngle: -45,
      thighAngle: 95,
      shankAngle: 80,
      ...COMPACT,
    }),
  },

  warmup_swimmers: {
    key: 'warmup_swimmers',
    name: 'Swimmers',
    equipment: 'bodyweight',
    restSec: 0,
    poseA: buildPose({
      hip: { x: 150, y: 122 },
      torsoAngle: 190,
      upperArmAngle: 190,
      forearmAngle: 190,
      thighAngle: 5,
      shankAngle: 5,
    }),
    poseB: buildPose({
      hip: { x: 150, y: 122 },
      torsoAngle: 175,
      upperArmAngle: 20,
      forearmAngle: 20,
      thighAngle: 5,
      shankAngle: 5,
    }),
  },

  warmup_hip_raises: {
    key: 'warmup_hip_raises',
    name: 'Hip Raises',
    equipment: 'bodyweight',
    restSec: 0,
    poseA: buildPose({
      hip: { x: 150, y: 126 },
      torsoAngle: 180,
      upperArmAngle: 60,
      forearmAngle: 45,
      thighAngle: -70,
      shankAngle: 95,
      torsoLen: 50,
      upperArmLen: 20,
      forearmLen: 18,
      thighLen: 35,
      shankLen: 35,
      neckLen: 16,
    }),
    poseB: buildPose({
      hip: { x: 150, y: 108 },
      torsoAngle: 163,
      upperArmAngle: 60,
      forearmAngle: 45,
      thighAngle: -50,
      shankAngle: 110,
      torsoLen: 50,
      upperArmLen: 20,
      forearmLen: 18,
      thighLen: 35,
      shankLen: 35,
      neckLen: 16,
    }),
  },

  warmup_jumping_jacks: {
    key: 'warmup_jumping_jacks',
    name: 'Jumping Jacks',
    equipment: 'bodyweight',
    restSec: 0,
    poseA: mergePoses(
      buildPose({
        hip: { x: 120, y: 90 },
        torsoAngle: -90,
        upperArmAngle: 100,
        forearmAngle: 100,
        thighAngle: 95,
        shankAngle: 88,
        torsoLen: 40,
        upperArmLen: 24,
        forearmLen: 21,
        thighLen: 32,
        shankLen: 32,
        neckLen: 13,
      }),
      buildPoseSecondary({
        hip: { x: 120, y: 90 },
        torsoAngle: -90,
        upperArmAngle: 80,
        forearmAngle: 80,
        thighAngle: 85,
        shankAngle: 92,
        torsoLen: 40,
        upperArmLen: 24,
        forearmLen: 21,
        thighLen: 32,
        shankLen: 32,
        neckLen: 13,
      }),
    ),
    poseB: mergePoses(
      buildPose({
        hip: { x: 120, y: 90 },
        torsoAngle: -90,
        upperArmAngle: -80,
        forearmAngle: -80,
        thighAngle: 115,
        shankAngle: 100,
        torsoLen: 40,
        upperArmLen: 24,
        forearmLen: 21,
        thighLen: 32,
        shankLen: 32,
        neckLen: 13,
      }),
      buildPoseSecondary({
        hip: { x: 120, y: 90 },
        torsoAngle: -90,
        upperArmAngle: -100,
        forearmAngle: -100,
        thighAngle: 65,
        shankAngle: 80,
        torsoLen: 40,
        upperArmLen: 24,
        forearmLen: 21,
        thighLen: 32,
        shankLen: 32,
        neckLen: 13,
      }),
    ),
  },

  // -------------------------------------------------------------- workout A
  a_lying_leg_curl: {
    key: 'a_lying_leg_curl',
    name: 'Lying Leg Curl',
    equipment: 'machine',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 140, y: 90 },
      torsoAngle: 180,
      upperArmAngle: 130,
      forearmAngle: 60,
      thighAngle: 5,
      shankAngle: 10,
      ...SEATED,
    }),
    poseB: buildPose({
      hip: { x: 140, y: 90 },
      torsoAngle: 180,
      upperArmAngle: 130,
      forearmAngle: 60,
      thighAngle: 5,
      shankAngle: -95,
      ...SEATED,
    }),
    frameShapes: [
      { kind: 'rect', x: 78, y: 84, w: 108, h: 10, rx: 3, fill: 'seat' },
      { kind: 'rect', x: 90, y: 94, w: 6, h: 34, fill: 'frameDark' },
      { kind: 'rect', x: 160, y: 94, w: 6, h: 34, fill: 'frameDark' },
    ],
    machine: { pulley: { x: 226, y: 100 }, stackTopRest: { x: 200, y: 44 }, stackTravel: 20, handJoint: 'ankle' },
    floor: { cx: 130, cy: 150, rx: 90, ry: 8 },
  },

  a_goblet_squat: {
    key: 'a_goblet_squat',
    name: 'Goblet Squat',
    equipment: 'free_weight',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 120, y: 84 },
      torsoAngle: -90,
      upperArmAngle: 70,
      forearmAngle: -100,
      thighAngle: 90,
      shankAngle: 90,
      ...COMPACT,
    }),
    poseB: buildPose({
      hip: { x: 120, y: 108 },
      torsoAngle: -75,
      upperArmAngle: 95,
      forearmAngle: -125,
      thighAngle: 150,
      shankAngle: 60,
      ...COMPACT,
    }),
    handheld: { joint: 'hand', kind: 'dumbbell' },
  },

  a_machine_row: {
    key: 'a_machine_row',
    name: 'Machine Row',
    equipment: 'cable',
    restSec: 90,
    // Ported verbatim from the Machine Row reference file (coordinates are
    // the reference's exact numbers, not re-derived via the angle rig).
    poseA: {
      hip: { x: 102, y: 92 },
      knee: { x: 141, y: 100 },
      ankle: { x: 153, y: 140.5 },
      shoulder: { x: 114.6, y: 41.6 },
      elbow: { x: 145.85, y: 43.58 },
      hand: { x: 172, y: 36 },
      head: { x: 118.5, y: 26.1 },
    },
    poseB: {
      hip: { x: 102, y: 92 },
      knee: { x: 141, y: 100 },
      ankle: { x: 153, y: 140.5 },
      shoulder: { x: 93.9, y: 40.6 },
      elbow: { x: 64.8, y: 51.2 },
      hand: { x: 88, y: 65.1 },
      head: { x: 91.4, y: 24.8 },
    },
    frameShapes: [
      { kind: 'rect', x: 150, y: 20, w: 60, h: 6, rx: 3, fill: 'frame' },
      { kind: 'rect', x: 200, y: 18, w: 6, h: 104, rx: 3, fill: 'frame' },
      { kind: 'rect', x: 58, y: 94, w: 72, h: 8, rx: 4, fill: 'seat' },
      { kind: 'rect', x: 64, y: 102, w: 6, h: 36, fill: 'frameDark' },
      { kind: 'rect', x: 118, y: 102, w: 6, h: 36, fill: 'frameDark' },
    ],
    machine: { pulley: { x: 178, y: 26 }, stackTopRest: { x: 192, y: 64 }, stackTravel: 22, plates: 5 },
  },

  a_push_up: {
    key: 'a_push_up',
    name: 'Push-Up',
    equipment: 'bodyweight',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 160, y: 110 },
      torsoAngle: 183,
      upperArmAngle: 95,
      forearmAngle: 95,
      thighAngle: 8,
      shankAngle: 8,
      torsoLen: 50,
      upperArmLen: 24,
      forearmLen: 21,
      thighLen: 40,
      shankLen: 30,
      neckLen: 14,
    }),
    poseB: buildPose({
      hip: { x: 160, y: 116 },
      torsoAngle: 183,
      upperArmAngle: 140,
      forearmAngle: 40,
      thighAngle: 8,
      shankAngle: 8,
      torsoLen: 50,
      upperArmLen: 24,
      forearmLen: 21,
      thighLen: 40,
      shankLen: 30,
      neckLen: 14,
    }),
    floor: { cx: 130, cy: 150, rx: 100, ry: 8 },
  },

  a_forearm_plank: {
    key: 'a_forearm_plank',
    name: 'Forearm Plank',
    equipment: 'bodyweight',
    restSec: 90,
    timeBased: true,
    poseA: buildPose({
      hip: { x: 160, y: 112 },
      torsoAngle: 183,
      upperArmAngle: 100,
      forearmAngle: 40,
      thighAngle: 8,
      shankAngle: 8,
      torsoLen: 50,
      upperArmLen: 24,
      forearmLen: 21,
      thighLen: 40,
      shankLen: 30,
      neckLen: 14,
    }),
    poseB: buildPose({
      hip: { x: 160, y: 113 },
      torsoAngle: 185,
      upperArmAngle: 100,
      forearmAngle: 40,
      thighAngle: 8,
      shankAngle: 8,
      torsoLen: 50,
      upperArmLen: 24,
      forearmLen: 21,
      thighLen: 40,
      shankLen: 30,
      neckLen: 14,
    }),
    floor: { cx: 130, cy: 150, rx: 100, ry: 8 },
  },

  // -------------------------------------------------------------- workout B
  b_back_extension: {
    key: 'b_back_extension',
    name: 'Back Extension',
    equipment: 'machine',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 140, y: 95 },
      torsoAngle: -20,
      upperArmAngle: 130,
      forearmAngle: 130,
      thighAngle: 100,
      shankAngle: 90,
      torsoLen: 50,
      upperArmLen: 31,
      forearmLen: 27,
      thighLen: 38,
      shankLen: 22,
      neckLen: 16,
    }),
    poseB: buildPose({
      hip: { x: 140, y: 95 },
      torsoAngle: -110,
      upperArmAngle: 40,
      forearmAngle: 40,
      thighAngle: 100,
      shankAngle: 90,
      torsoLen: 50,
      upperArmLen: 31,
      forearmLen: 27,
      thighLen: 38,
      shankLen: 22,
      neckLen: 16,
    }),
    frameShapes: [
      { kind: 'rect', x: 118, y: 90, w: 44, h: 12, rx: 4, fill: 'seat' },
      { kind: 'rect', x: 126, y: 102, w: 6, h: 40, fill: 'frameDark' },
      { kind: 'rect', x: 150, y: 102, w: 6, h: 40, fill: 'frameDark' },
    ],
  },

  b_reverse_lunge: {
    key: 'b_reverse_lunge',
    name: 'Reverse Lunge',
    equipment: 'bodyweight',
    restSec: 90,
    perSide: true,
    poseA: mergePoses(
      buildPose({
        hip: { x: 120, y: 80 },
        torsoAngle: -90,
        upperArmAngle: 80,
        forearmAngle: 80,
        thighAngle: 95,
        shankAngle: 85,
        ...COMPACT,
      }),
      buildPoseSecondary({
        hip: { x: 120, y: 80 },
        torsoAngle: -90,
        upperArmAngle: 110,
        forearmAngle: 110,
        thighAngle: 100,
        shankAngle: 90,
        ...COMPACT,
      }),
    ),
    poseB: mergePoses(
      buildPose({
        hip: { x: 120, y: 90 },
        torsoAngle: -90,
        upperArmAngle: 110,
        forearmAngle: 110,
        thighAngle: 95,
        shankAngle: 85,
        ...COMPACT,
      }),
      buildPoseSecondary({
        hip: { x: 120, y: 90 },
        torsoAngle: -90,
        upperArmAngle: 80,
        forearmAngle: 80,
        thighAngle: 60,
        shankAngle: 170,
        ...COMPACT,
      }),
    ),
  },

  b_reverse_fly: {
    key: 'b_reverse_fly',
    name: 'Reverse Fly',
    equipment: 'machine',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 130, y: 95 },
      torsoAngle: -95,
      upperArmAngle: -10,
      forearmAngle: -10,
      thighAngle: 15,
      shankAngle: 80,
      ...SEATED,
    }),
    poseB: buildPose({
      hip: { x: 130, y: 95 },
      torsoAngle: -95,
      upperArmAngle: 170,
      forearmAngle: 170,
      thighAngle: 15,
      shankAngle: 80,
      ...SEATED,
    }),
    frameShapes: [
      { kind: 'rect', x: 108, y: 90, w: 44, h: 12, rx: 4, fill: 'seat' },
      { kind: 'rect', x: 116, y: 102, w: 6, h: 40, fill: 'frameDark' },
      { kind: 'rect', x: 140, y: 102, w: 6, h: 40, fill: 'frameDark' },
      { kind: 'rect', x: 40, y: 30, w: 6, h: 90, rx: 3, fill: 'frame' },
    ],
    machine: { pulley: { x: 55, y: 55 }, stackTopRest: { x: 40, y: 85 }, stackTravel: 18 },
  },

  b_chest_press: {
    key: 'b_chest_press',
    name: 'Chest Press',
    equipment: 'machine',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 150, y: 95 },
      torsoAngle: -92,
      upperArmAngle: 175,
      forearmAngle: 170,
      thighAngle: 15,
      shankAngle: 80,
      ...SEATED,
    }),
    poseB: buildPose({
      hip: { x: 150, y: 95 },
      torsoAngle: -92,
      upperArmAngle: 175,
      forearmAngle: -15,
      thighAngle: 15,
      shankAngle: 80,
      ...SEATED,
    }),
    frameShapes: [
      { kind: 'rect', x: 128, y: 90, w: 44, h: 12, rx: 4, fill: 'seat' },
      { kind: 'rect', x: 136, y: 102, w: 6, h: 40, fill: 'frameDark' },
      { kind: 'rect', x: 160, y: 102, w: 6, h: 40, fill: 'frameDark' },
      { kind: 'rect', x: 40, y: 20, w: 6, h: 100, rx: 3, fill: 'frame' },
    ],
    machine: { pulley: { x: 55, y: 50 }, stackTopRest: { x: 40, y: 80 }, stackTravel: 18 },
  },

  b_side_plank: {
    key: 'b_side_plank',
    name: 'Side Plank',
    equipment: 'bodyweight',
    restSec: 90,
    perSide: true,
    timeBased: true,
    poseA: buildPose({
      hip: { x: 150, y: 110 },
      torsoAngle: -165,
      upperArmAngle: 100,
      forearmAngle: 190,
      thighAngle: 15,
      shankAngle: 15,
      ...SEATED,
    }),
    poseB: buildPose({
      hip: { x: 150, y: 111.5 },
      torsoAngle: -163,
      upperArmAngle: 100,
      forearmAngle: 190,
      thighAngle: 15,
      shankAngle: 15,
      ...SEATED,
    }),
    floor: { cx: 150, cy: 148, rx: 95, ry: 8 },
  },

  // -------------------------------------------------------------- workout C
  c_hip_thrust: {
    key: 'c_hip_thrust',
    name: 'Hip Thrust',
    equipment: 'free_weight',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 150, y: 120 },
      torsoAngle: 180,
      upperArmAngle: 30,
      forearmAngle: 150,
      thighAngle: -70,
      shankAngle: 100,
      torsoLen: 50,
      upperArmLen: 20,
      forearmLen: 18,
      thighLen: 40,
      shankLen: 38,
      neckLen: 16,
    }),
    poseB: buildPose({
      hip: { x: 150, y: 95 },
      torsoAngle: 160,
      upperArmAngle: 30,
      forearmAngle: 150,
      thighAngle: -70,
      shankAngle: 100,
      torsoLen: 50,
      upperArmLen: 20,
      forearmLen: 18,
      thighLen: 40,
      shankLen: 38,
      neckLen: 16,
    }),
    handheld: { joint: 'hip', kind: 'dumbbell' },
    frameShapes: [{ kind: 'rect', x: 72, y: 116, w: 42, h: 10, rx: 2, fill: 'seat' }],
    floor: { cx: 150, cy: 150, rx: 95, ry: 8 },
  },

  c_leg_press: {
    key: 'c_leg_press',
    name: 'Leg Press',
    equipment: 'machine',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 80, y: 95 },
      torsoAngle: -110,
      upperArmAngle: 160,
      forearmAngle: 160,
      thighAngle: 10,
      shankAngle: -60,
      torsoLen: 50,
      upperArmLen: 22,
      forearmLen: 20,
      thighLen: 40,
      shankLen: 38,
      neckLen: 16,
    }),
    poseB: buildPose({
      hip: { x: 80, y: 95 },
      torsoAngle: -110,
      upperArmAngle: 160,
      forearmAngle: 160,
      thighAngle: 5,
      shankAngle: -15,
      torsoLen: 50,
      upperArmLen: 22,
      forearmLen: 20,
      thighLen: 40,
      shankLen: 38,
      neckLen: 16,
    }),
    frameShapes: [
      { kind: 'rect', x: 30, y: 40, w: 42, h: 12, rx: 4, fill: 'seat' },
      { kind: 'line', x1: 40, y1: 118, x2: 72, y2: 118, stroke: 'frameDark', width: 8 },
    ],
    machine: { pulley: { x: 45, y: 40 }, stackTopRest: { x: 20, y: 55 }, stackTravel: 18, handJoint: 'ankle' },
  },

  c_lat_pulldown: {
    key: 'c_lat_pulldown',
    name: 'Lat Pulldown',
    equipment: 'cable',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 150, y: 113 },
      torsoAngle: -90,
      upperArmAngle: -100,
      forearmAngle: -90,
      thighAngle: 15,
      shankAngle: 80,
      torsoLen: 50,
      upperArmLen: 31,
      forearmLen: 27,
      thighLen: 40,
      shankLen: 35,
      neckLen: 16,
    }),
    poseB: buildPose({
      hip: { x: 150, y: 113 },
      torsoAngle: -90,
      upperArmAngle: 140,
      forearmAngle: 60,
      thighAngle: 15,
      shankAngle: 80,
      torsoLen: 50,
      upperArmLen: 31,
      forearmLen: 27,
      thighLen: 40,
      shankLen: 35,
      neckLen: 16,
    }),
    frameShapes: [
      { kind: 'rect', x: 128, y: 106, w: 44, h: 12, rx: 4, fill: 'seat' },
      { kind: 'rect', x: 136, y: 118, w: 6, h: 30, fill: 'frameDark' },
      { kind: 'rect', x: 160, y: 118, w: 6, h: 30, fill: 'frameDark' },
      { kind: 'rect', x: 145, y: 16, w: 6, h: 90, rx: 3, fill: 'frame' },
    ],
    machine: { pulley: { x: 150, y: 20 }, stackTopRest: { x: 195, y: 46 }, stackTravel: 22 },
  },

  c_machine_fly: {
    key: 'c_machine_fly',
    name: 'Machine Fly',
    equipment: 'machine',
    restSec: 90,
    poseA: buildPose({
      hip: { x: 150, y: 98 },
      torsoAngle: -93,
      upperArmAngle: 160,
      forearmAngle: 160,
      thighAngle: 15,
      shankAngle: 80,
      ...SEATED,
    }),
    poseB: buildPose({
      hip: { x: 150, y: 98 },
      torsoAngle: -93,
      upperArmAngle: -10,
      forearmAngle: -10,
      thighAngle: 15,
      shankAngle: 80,
      ...SEATED,
    }),
    frameShapes: [
      { kind: 'rect', x: 128, y: 93, w: 44, h: 12, rx: 4, fill: 'seat' },
      { kind: 'rect', x: 136, y: 105, w: 6, h: 38, fill: 'frameDark' },
      { kind: 'rect', x: 160, y: 105, w: 6, h: 38, fill: 'frameDark' },
      { kind: 'rect', x: 40, y: 30, w: 6, h: 90, rx: 3, fill: 'frame' },
    ],
    machine: { pulley: { x: 55, y: 55 }, stackTopRest: { x: 40, y: 85 }, stackTravel: 18 },
  },

  c_cable_lateral_raise: {
    key: 'c_cable_lateral_raise',
    name: 'Cable Lateral Raise',
    equipment: 'cable',
    restSec: 90,
    perSide: true,
    poseA: buildPose({
      hip: { x: 130, y: 84 },
      torsoAngle: -90,
      upperArmAngle: 100,
      forearmAngle: 100,
      thighAngle: 90,
      shankAngle: 90,
      ...COMPACT,
    }),
    poseB: buildPose({
      hip: { x: 130, y: 84 },
      torsoAngle: -90,
      upperArmAngle: 5,
      forearmAngle: 5,
      thighAngle: 90,
      shankAngle: 90,
      ...COMPACT,
    }),
    frameShapes: [{ kind: 'rect', x: 68, y: 136, w: 6, h: 16, rx: 2, fill: 'frame' }],
    machine: { pulley: { x: 71, y: 138 }, stackTopRest: { x: 50, y: 110 }, stackTravel: 18 },
  },
}

export function getMotionGuide(key: string): ExerciseMotionData | undefined {
  return motionGuides[key]
}

export type { Pose }
